{% set version = "0.91.0" %}
{% set sha256 = "f21044d721461310f0605b7a83fba6cba78d1703456042809bde9d772c9b5c95" %}

package:
  name: pydstool
  version: {{ version }}

source:
  fn: pydstool-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/PyDSTool/PyDSTool-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - six
    - scipy
    - numpy

  run:
    - python
    - six
    # package is not compatible with scipy 1.* due to version check in the code
    - {{ pin_compatible('scipy') }}
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - PyDSTool
    - PyDSTool.Generator
    - PyDSTool.PyCont
    - PyDSTool.Toolbox
    - PyDSTool.Toolbox.optimizers
    - PyDSTool.Toolbox.optimizers.criterion
    - PyDSTool.Toolbox.optimizers.helpers
    - PyDSTool.Toolbox.optimizers.line_search
    - PyDSTool.Toolbox.optimizers.optimizer
    - PyDSTool.Toolbox.optimizers.step
    - PyDSTool.core
    - PyDSTool.core.codegenerators

about:
  home: http://www.ni.gsu.edu/~rclewley/PyDSTool/FrontPage.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: |
    PyDSTool is a sophisticated & integrated simulation and analysis environment
    for dynamical systems models of physical systems (ODEs, DAEs, maps, and
    hybrid systems).
  doc_url: http://www.ni.gsu.edu/~rclewley/PyDSTool/ProjectOverview.html
  dev_url: https://github.com/robclewley/pydstool

extra:
  recipe-maintainers:
    - ChrisRackauckas
