appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IfgjSineoCcDIsVUij5j3JMGdaNX/CYuxwoCufffW1Syi+KLe2bJF25TOCYQKVu6G9quGxO3yrgf0mFyDIrQ8sOmkHPB5o4XeD7u6zzZa+uuRojq4nkzYueMdSlTKWWse4m14DmpkoaZ2GJjAykBwSHXf59LeZF0kqNpAvzviBpbASuc/a7qi6Og9mqUM9gGkQfCKyiYXuXv8+7aNOPSPNm58Su5SxokXTokx8ViqPJp0znroo7AzvkIRbQzsiZzHuvNXC+du2WEIKc/UzjehKl6Hxg6GM1LNRsmZeRbeVVXmyZoXA1yQ0IqOBR/UI3lwC8BXC9bFY1w8k4TBTylv8YIGVD3H4l65g+MqT0QfYfr55qWG3D2p73zUcw1UEwWqFONZqbW7hjRzuOG5TUxdO4B6fdWanCLtX2YvYGm7NhOymt5NyJCned+HQuqffDbisSYvc198EZ7qBm40QMBaAkNG9rVSgzl8pkDrRkaQckwpDJwihA/BkiW3eOfGJU7KoMIZgJEdIeh5JgnnmxQbK+LYb6TBOZB2WUDH//55sAGn7E8r2iLz5wNrD1SBOk3TSKeSbCgIlYJ1rksH9n8C7OU4WYjrwwpT79zkICWLcppd8c1vYs2C4Ku9AsBn/CWoTq+cHVoe/zcDerrhcV9WPLakFL44PhEOEWz/aMUxYA=}
